# Generated by Django 5.2.7 on 2025-11-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contact_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Отметьте, если продукт должен быть виден на сайте.",
                verbose_name="Опубликовано",
            ),
        ),
    ]
